#fastlane_version "1.13.1"

default_platform :ios

platform :ios do

  before_all do
    	cocoapods
#	sh "../extract_supported_currencies.py"

      xctest({
        workspace: "picnic.xcworkspace",
        scheme: "picnic",
        sdk: "iphonesimulator",
        destination: "platform=iOS Simulator,name=iPhone 6,OS=latest"
    })
  end

  desc "Deploy a new Beta Build to Apple TestFlight"
  lane :deploy do
      slack({
        message: "Starting deploy"
      })
      sh "../increment_build_number.sh"
	gym
#      snapshot
      deliver
      sh "../commit_release.sh"
      slack({
        message: "Finished deploying to appstore"
      })
  end

desc "test"
  lane :test do
      slack({
        message: "Snapshot"
      })
      snapshot
      slack({
        message: "Finished"
      })
  end


  desc "Release a new Version on iTunes Connect"
  lane :release do
      slack({
        message: "Starting release"
      })
      sh "../increment_version_number.sh"
      ipa({
        scheme: "picnic"
        })

      deliver
      sh "../commit_release.sh"
      slack({
        message: "Finished deploying to appstore"
      })
  end

  desc "snapshot"
    lane:snapshot do
      snapshot
    end


  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack({
    #   message: "Successfully deployed new App Update."
    # })
  end


  error do |lane, exception|
     slack({
       message: exception.message,
       success: false
     })
  end

end


# More information about multiple platforms in fastlane: 
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
