#fastlane_version "1.13.1"

default_platform :ios

platform :ios do

  before_all do
	ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    	cocoapods
#	sh "../extract_supported_currencies.py"
  end

  desc "Deploy a new Beta Build to Apple TestFlight"
  lane :deploy do
      slack({
        message: "Starting deploy"
      })
      sh "../increment_build_number.sh"
	gym
#      snapshot
      deliver
      sh "../commit_release.sh"
      slack({
        message: "Finished deploying to appstore"
      })
  end

desc "test"
  lane :test do
    xctest({
        workspace: "picnic.xcworkspace",
        scheme: "picnic",
        sdk: "iphonesimulator",
        destination: "platform=iOS Simulator,name=iPhone 6,OS=latest"
    })
      slack({
        message: "Finished"
      })
  end


  desc "Release a new Version on iTunes Connect"
  lane :release do
      slack({
        message: "Starting release"
      })
      sh "../increment_version_number.sh"
      ipa({
        scheme: "picnic"
        })

      deliver
      sh "../commit_release.sh"
      slack({
        message: "Finished deploying to appstore"
      })
  end

  error do |lane, exception|
     slack({
       message: exception.message,
       success: false
     })
  end

end


# More information about multiple platforms in fastlane: 
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
